version: '3.8'

services:
  est-mit-payment:
    build:
      target: development
    image: est-mit-payment-development
    container_name: est-mit-payment-test
    entrypoint: dotnet test ./EST.MIT.Payment.Function.Test/EST.MIT.Payment.Function.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'
    volumes:
      - ./test-output:/home/dotnet/EST.MIT.Payment.Function.Test/test-output
